### ISSUE TITLE
Improve the reference to different data

### ISSUE THREAD

**Issue by labrosse** [StagPython/StagPy#14]
It would be good to have data accessed by names instead of column numbers, e.g. in tseries or rprof, so they are more easily accessed from stagyydata. We then need to list all accessible data in the documentation and the way it accessed.

**Comment by amorison** [comment]
Solved by the merge 9551be6df60e353f5edbb837b079b676020fa749. Rprof and time series data are now pandas DataFrame. The command line interface of time and rprof have been improved to take advantage of this. The documentation has been updated subsequently.
