### ISSUE TITLE
Add option to have plots in dimensions

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#23]
By default all plots are in non-dimensional space. An option to rescale variables back to dimensions should be available.

**Comment by amorison** [comment]
This is done with commits 59376f4c07f6fd36c6f72ba74fbd63b30c7adccf and 2dd52bdffb52bd3e402a8c1c928084bb2d3e9b9a. The approach implemented here is rather crude and not very flexible. That should be fine for now, but maybe it would be worth using an external library such as Pint to gain flexibility.
