### ISSUE TITLE
Time averaged profiles 

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#40]
Add an option to plot time averaged profiles

**Comment by amorison** [comment]
We already have that, it's the `average` switch (`a` as a shortened version) of the `rprof` command, see `stagpy rprof --help`. For example, to obtain the average temperature profile over all timesteps, you can run `stagpy rprof -o Tmean -s=: +a`.

Beware that it does not behave correctly if the radial grid was changed during the simulation.
