### ISSUE TITLE
stagpy var field

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#46]
implement new command option: `stagpy var field` would give variables relative to the field command, `stagpy var rprof` would give variables relative to the rprof etc.

**Comment by amorison** [comment]
Solved by 1406d7a984364b805aadec83fe7f5b2de8d1f8ba

The `var` subcommand now understands the `--field`, `--rprof`, `--time` and `--plates` options. If none is specified, all var are displayed, otherwise only var of the corresponding used option(s) will be displayed.
