### ISSUE TITLE
wrong mesh size 

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#52]
```
from stagpy.stagyydata import StagyyData
sdat = StagyyData('../') 
xmesh = sdat.snaps[0].geom.x_mesh
```

xmesh does not have correct dimensions if files with surface variables like topography are present

**Comment by amorison** [comment]
This is solved by 6e8126ddd3978ffff6d2cbd52c67c82024e912a1. Surface fields (topography and geoid) are now accessible via the new `sfields` attribute of `Step` objects instead of the `fields` attribute to avoid collision between geometries.
