### ISSUE TITLE
sdat.plotfiled()

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#56]
having a feature in StagyyData class for plotting field, i.e. sdat.plotfiled(mynewfield)

**Comment by amorison** [comment]
I'd like to avoid to do that to keep features separated. The `StagyyData` class is already quite complicated and its only purpose should be to access StagYY output data.

People should use functions of the `stagpy.field` submodule to plot field data.

**Comment by mulvrova** [comment]
actually it already exists

field.plot_scalar(sdat.snaps[100], 'T', field=squeeze(temp_mean))
