### ISSUE TITLE
info on specific snapshot

### ISSUE THREAD

**Issue by labrosse** [StagPython/StagPy#58]
The command info should accept the -s option to apply it to a specific snapshot. For example,
stagpy info -s 80
would provide the basic info on snapshot 80, like its time, mean value of different fields etc.

**Comment by amorison** [comment]
This is implemented with commit ae4d44ba27b4ae79fedb45b78128968495af9c81

The `stagpy info` command now has a more flexible output. It can prints info on a arbitary set of snapshots or timesteps (passed on with the usual `-s` or `-t` options), the information printed for each timestep is a list of time series variable. For example, `stagpy info -t=0,-1 -o=t,vmax` will print the time and max velocity for the first and last time steps.
