### ISSUE TITLE
plot reference state

### ISSUE THREAD

**Issue by mulvrova** [StagPython/StagPy#62]

**Comment by mulvrova** [comment]
reading reference state should be similar as reading rprof file. output would be a plot with density for each phase and density profile for combined adiabat. the command using CL could be e.g. `stagpy refstate`

**Comment by amorison** [comment]
Implemented with eb302a3be137ae51141b641f83969f20186a031f (the parser itself) and 4097c885c54d041f86432b7d35af99a11b5a8a6b (the command line).

There is still room for improvement and new features on top of the command I implemented which merely plots the adiabats for all the systems and the combined one for the chosen variables (comma-separated list of variables, e.g. `stagpy refstate -o=T,rho,expan,tcond`), as usual see `stagpy var` for the available variable names. Note than some profiles don't have every variable available, there was a recent fix ptackley/StagYY#437
